tstats_npb<-read.csv("C:/Users/T-Reio/Master_thesis/team_stats_npb.csv",header=T,sep=",")
summary(tstats_npb)
Avg<-tstats_npb$AVG
Obp<-tstats_npb$OBP
WA<-tstats_npb$WA
Slg<-tstats_npb$SLG
Runs<-tstats_npb$Runs
plot(Avg,Runs)
plot(Obp,Runs)
RegObp<-lm(Runs~Obp,data=tstats_npb)
RegAvg<-lm(Runs~Avg,data=tstats_npb)
RegSlg<-lm(Runs~Slg,data=tstats_npb)
summary(RegAvg)
summary(RegSlg)
summary(RegObp)
cor(Avg,Runs)
cor(Obp,Runs)
cor(Slg,Runs)