library(data.table)
tstats_npb<-fread("C:/Users/T-Reio/Master_thesis/team_stats_npb.csv",header=T,sep=",")
summary(tstats_npb)
Avg<-tstats_npb$AVG
Obp<-tstats_npb$OBP
WA<-tstats_npb$WA
Slg<-tstats_npb$SLG
Runs<-tstats_npb$Runs
Yrs<-as.factor(tstats_npb$year)
League<-tstats_npb$LEAGUE
plot(Avg,Runs)
plot(Obp,Runs)
plot(Slg,Runs)
RegObp<-lm(Runs~Obp+Yrs+League,data=tstats_npb)
RegAvg<-lm(Runs~Avg+Yrs+League,data=tstats_npb)
RegSlg<-lm(Runs~Slg+Yrs+League,data=tstats_npb)
OPS=Obp+Slg
RegOPS<-lm(Runs~OPS+Yrs+League,data=tstats_npb)
summary(RegAvg)
summary(RegSlg)
summary(RegObp)
summary(RegOPS)
cor(Avg,Runs)
cor(Obp,Runs)
cor(Slg,Runs)
cor(Avg,WA)
cor(Obp,WA)
cor(Slg,WA)
WARegObp<-lm(WA~Obp+Yrs+League,data=tstats_npb)
WARegAvg<-lm(WA~Avg+Yrs+League,data=tstats_npb)
WARegSlg<-lm(WA~Slg+Yrs+League,data=tstats_npb)
WARegOPS<-lm(WA~OPS+Yrs+League,data=tstats_npb)
summary(WARegAvg)
summary(WARegSlg)
summary(WARegObp)
summary(WARegOPS)